version: "3.9"

services:

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: bank_accounts
      POSTGRES_USER: bank_user
      POSTGRES_PASSWORD: bank_password
    ports:
      - "5432:5432"

  discovery-server:
    build: ./discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"

  config-server:
    build: ./config-server
    container_name: config-server
    ports:
      - "8888:8888"
    depends_on:
      - discovery-server

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - discovery-server
      - config-server

  accounts-service:
    build: ./accounts-service
    container_name: accounts-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - discovery-server
      - config-server

  cash-service:
    build: ./cash-service
    container_name: cash-service
    ports:
      - "8082:8082"
    depends_on:
      - discovery-server
      - config-server
      - accounts-service
      - blocker-service
      - notifications-service

  transfer-service:
    build: ./transfer-service
    container_name: transfer-service
    ports:
      - "8083:8083"
    depends_on:
      - discovery-server
      - config-server
      - accounts-service
      - blocker-service
      - notifications-service
      - exchange-service

  exchange-service:
    build: ./exchange-service
    container_name: exchange-service
    ports:
      - "8084:8084"
    depends_on:
      - discovery-server
      - config-server

  blocker-service:
    build: ./blocker-service
    container_name: blocker-service
    ports:
      - "8085:8085"
    depends_on:
      - discovery-server
      - config-server

  notifications-service:
    build: ./notifications-service
    container_name: notifications-service
    ports:
      - "8086:8086"
    depends_on:
      - discovery-server
      - config-server

  exchange-generator-service:
    build: ./exchange-generator-service
    container_name: exchange-generator-service
    ports:
      - "8087:8087"
    depends_on:
      - discovery-server
      - config-server
      - exchange-service
  front-ui:
    build: ./front-ui
    container_name: front-ui
    ports:
      - "8090:8090"
    depends_on:
      - discovery-server
      - config-server
      - accounts-service
      - cash-service
      - transfer-service
      - exchange-service