server:
  port: 8082

spring:
  application:
    name: cash-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/bankapp-realm
      client:
        registration:
          keycloak:
            provider: keycloak
            authorization-grant-type: client_credentials
            client-id: cash-service-client
            client-secret: 2XGxtQqBA0MlCMTmpnNj6Z2x60Ai0WIi
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/realms/bankapp-realm

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info

services:
  accounts-service:
    url: http://accounts-service:8081
  blocker-service:
    url: http://blocker-service:8085
  notification-service:
    url: http://notifications-service:8086