server:
  port: 8082

spring:
  application:
    name: cash-service

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info

services:
  accounts-service:
    url: http://accounts-service:8081
  blocker-service:
    url: http://blocker-service:8085
  notification-service:
    url: http://notifications-service:8086