server:
  port: 8087

spring:
  application:
    name: exchange-generator-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

services:
  exchange-service:
    url: http://localhost:8084

management:
  endpoints:
    web:
      exposure:
        include: health,info