server:
  port: 8090

spring:
  application:
    name: front-ui
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            authorization-grant-type: client_credentials
            client-id: front-ui-client
            client-secret: ZPncHR0elrxiUIONpaYErdppm2IySBCK
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/realms/bankapp-realm

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/

services:
  accounts-service:
    url: http://accounts-service:8081
  cash-service:
    url: http://cash-service:8082
  transfer-service:
    url: http://transfer-service:8083
  exchange-service:
    url: http://exchange-service:8084

management:
  endpoints:
    web:
      exposure:
        include: health,info