server:
  port: 8085

spring:
  application:
    name: blocker-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/bankapp-realm

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/